# Numpy: Basic Operations
**What is Numpy?**

NumPy is the fundamental package for scientific computing in Python. It is a Python library that provides a **multidimensional array object** (*In Python,* *an array is a data structure that stores multiple values in a single variable*), various derived objects (such as masked arrays and matrices), and an assortment of routines for fast operations on arrays, including mathematical, logical, shape manipulation, sorting, selecting, I/O, discrete Fourier transforms, basic linear algebra, basic statistical operations, random simulation and much more.

**(Basically a library used for the math part of ML)**


**Why Numpy?**

**1.Faster Than Python Lists**:
NumPy arrays (ndarray) are implemented in C, making them much faster than Python lists.

**2.Supports Large Datasets Efficiently**:It stores data more compactly than Python lists, reducing memory consumption.

**3.Extensive Mathematical & Statistical Functions**: Extensive Mathematical & Statistical Functions

**4.Essential for Machine Learning & AI**:
Many libraries like TensorFlow, Scikit-Learn and Pandas have the foundation of Numpy



In [3]:
import numpy as np

# Create a ndarray

In [ ]:
# This is a 1d Array
a = np.array([1,2,3])
print(a)

[1 2 3]


In [ ]:
# 2d Array : A matrix
b = np.array([[1,2,3],[4,5,6]])
print(b)

[[1 2 3]
 [4 5 6]]


In [ ]:
# 3d array : A tensor
c = np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])
print(c)

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]


In [ ]:
# Create array of any data type
np.array([1,2,3],dtype = float)

array([1., 2., 3.])

In [ ]:
np.array([1,2,3],dtype = bool)

array([ True,  True,  True])

In [ ]:
# Create an array within a given range
np.arange(1,11)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [ ]:
# Check the array dimension
c = np.arange(1,11)
c.ndim # is a 1 d array

1

In [ ]:
# To change the dimension or shape of a given array
c= np.arange(1,11)
print(c) # 1d array

np.arange(1,11).reshape(2,5) # 2d array of 2 rows and 5 columns

[ 1  2  3  4  5  6  7  8  9 10]


array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [ ]:
# np.ones and np.zeros np.random are used to create arrays filled with ones or zeros or random numbers betn 0-1 respectively.
# commonly used for intializing arrays in DeepLearning
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [ ]:
np.zeros((4,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [ ]:
np.random.random((3,4))

array([[0.59402609, 0.0526132 , 0.52177884, 0.85884801],
       [0.84737015, 0.28967997, 0.70271723, 0.68651892],
       [0.62948456, 0.40480602, 0.92609109, 0.06005738]])

In [ ]:
# To generate an array of evenly spaced numbers over a specified range
# np.linspace(Lowerlimit,Upperlimit,no.of items )
np.linspace(-10,10,10)

array([-10.        ,  -7.77777778,  -5.55555556,  -3.33333333,
        -1.11111111,   1.11111111,   3.33333333,   5.55555556,
         7.77777778,  10.        ])

In [ ]:
# To generate an Identity Matrix
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

# Array Attributes

In [ ]:
a1= np.arange(10)
a2= np.arange(12,dtype=float).reshape(3,4) # (3,4) = (rows,column)
a3= np.arange(8).reshape(2,2,2) # (2,2,2) = (no. of 2 day arrays,row,column)


In [ ]:
# Check Dimensions
a1.ndim

1

In [ ]:
# Check its shape
a2.shape

(3, 4)

In [ ]:
# Check number of items
a3.size

8

In [ ]:
# How much memory an array occupies , in bytes
# int32 = 4 bytes , int64 = 8 bytes
a2.itemsize

8

In [ ]:
# Find the data type of the array
a1.dtype

dtype('int64')

# Changing data types

In [ ]:
# Changing the data type
a3.astype(np.int32) # int64 to innt32

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]], dtype=int32)

# Array Operations(mathematical)


In [ ]:
a1 = np.arange(12).reshape(3,4)
a2 = np.arange(12,24).reshape(3,4)
a3 = np.arange(8).reshape(2,2,2)
a3

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

In [ ]:
# Scalar opertions : Between an array and a scalar
# Arithmetic
# Multipy every element w 2
a1 *2

array([[ 0,  2,  4,  6],
       [ 8, 10, 12, 14],
       [16, 18, 20, 22]])

In [ ]:
# add +2 to every element
a1 + 2

array([[ 2,  3,  4,  5],
       [ 6,  7,  8,  9],
       [10, 11, 12, 13]])

In [ ]:
# Relational operators
a2 > 5
# will return true if element is greater than 5


array([[ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True]])

In [ ]:
a2 == 5


array([[False, False, False, False],
       [False, False, False, False],
       [False, False, False, False]])

In [ ]:
# vector operations : Between 2 arrays
# can perform if shape of 2 arrays is same
a1 + a2 # with a3 would throw an error

array([[12, 14, 16, 18],
       [20, 22, 24, 26],
       [28, 30, 32, 34]])

# Array Functions

In [4]:
a1 = np.random.random((3,3))
a1 = np.round(a1*100)
a1

array([[ 8., 89.,  0.],
       [72., 41., 62.],
       [27., 48., 61.]])

In [5]:
# Finds the biggest number
np.max(a1) #similarly np.min()

np.float64(89.0)

In [6]:
# Sum of all elements

np.sum(a1) #similarly for product np.prod()

np.float64(408.0)

In [7]:
# axis = 0 -> column wise
# axis = 1 -> row wise
# column wise multiplication (35 * 92 * 63)
np.prod(a1, axis = 0)

array([ 15552., 175152.,      0.])

In [8]:
 np.max(a1,axis = 1)

array([89., 72., 61.])

In [9]:
# Statistical operations
np.mean(a1)

np.float64(45.333333333333336)

In [11]:
np.median(a1)

np.float64(48.0)

In [13]:
np.var(a1) #variance

np.float64(772.4444444444443)

In [14]:
np.std(a1) #standard deviation

np.float64(27.792884780901108)

In [15]:
# trignometric functions
# not exactly useful
np.sin(a1)

array([[ 0.98935825,  0.86006941,  0.        ],
       [ 0.25382336, -0.15862267, -0.7391807 ],
       [ 0.95637593, -0.76825466, -0.96611777]])

In [20]:
# dot product : when no. of column of first matrix = no. of rows of second matrix
a3 = np.arange(12).reshape(3,4)
a4 = np.arange(12,24).reshape(4,3)

np.dot(a3,a4)


array([[114, 120, 126],
       [378, 400, 422],
       [642, 680, 718]])

In [22]:
# Log and exponents
np.log(a1)


<ipython-input-22-3b6228ba0d10>:2: RuntimeWarning: divide by zero encountered in log
  np.log(a1)


array([[2.07944154, 4.48863637,       -inf],
       [4.27666612, 3.71357207, 4.12713439],
       [3.29583687, 3.87120101, 4.11087386]])

In [23]:
np.exp(a1)

array([[2.98095799e+03, 4.48961282e+38, 1.00000000e+00],
       [1.85867175e+31, 6.39843494e+17, 8.43835667e+26],
       [5.32048241e+11, 7.01673591e+20, 3.10429794e+26]])

In [28]:
a = np.random.random((2,3))*100
a

array([[76.59958743, 54.12714437, 62.05618528],
       [38.98238782, 38.21813388, 81.50510863]])

In [29]:
# round / floor / ceil

np.round(a) # -> rounds to the nearest even number


array([[77., 54., 62.],
       [39., 38., 82.]])

In [30]:
np.floor(a) #-> rounds off behind

array([[76., 54., 62.],
       [38., 38., 81.]])

In [31]:
np.ceil(a) # -> rounds a number upward to the nearest whole number.

array([[77., 55., 63.],
       [39., 39., 82.]])

# Indexing and Slicing

In [65]:
a1 = np.arange(10)
a2 = np.arange(12).reshape(3,4)
a3 = np.arange(27).reshape(3,3,3)

# P.s : first row's and column's indexing starts with 0 , so to access first row is basically the zeroth row

In [34]:
# Indexing
# Positive indexing : 0 to n-1
# Negative indexing : -1 to -n
a1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [35]:
a1[-1] # last item

np.int64(9)

In [36]:
a2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [37]:
# to locate a certain number say 6
# array[row,column] of that element
a2[1,2]

np.int64(6)

In [38]:
a3

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

In [40]:
# [which 2d array, row, column]
a3[1,0,1]

np.int64(5)

In [43]:
# Slicing
a1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [45]:
# To extract numbers 2,3,4
a1[2:5] # last number isnt included

array([2, 3, 4])

In [46]:
a1[2:5:2] # adds step size : Takes every second element

array([2, 4])

In [47]:
# 2D array slicing
a2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [51]:
# here ':' returns everything based on where you put it.
# if [row, :] , it will return the all columns in that row
a2[0,:]

array([0, 1, 2, 3])

Practice questions : slicing

In [52]:
a2[:,0]

array([0, 4, 8])

In [53]:
a2[1:,1:3]

array([[ 5,  6],
       [ 9, 10]])

In [57]:
a2[::2,::3] #::2 skips 1 row, ::3 skips 2 columns

array([[ 0,  3],
       [ 8, 11]])

In [59]:
a2[0::2,1::2] # :: used for skipping , asks for step size

array([[ 1,  3],
       [ 9, 11]])

In [60]:
a2[0:2,0:3] # start : end(not included row/col)

array([[0, 1, 2],
       [4, 5, 6]])

In [63]:
a2[1,0::3]

array([4, 7])

In [64]:
a2[:2, 1:]

array([[1, 2, 3],
       [5, 6, 7]])

In [66]:
# 3D array slicing
a3

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [70]:
# for a specific 2d array
a3[1,:,:]

array([[ 9, 10, 11],
       [12, 13, 14],
       [15, 16, 17]])

In [71]:
a3[0,1,:]

array([3, 4, 5])

In [72]:
a3[1,:,1]

array([10, 13, 16])

In [73]:
a3[2,1:,1:]

array([[22, 23],
       [25, 26]])

In [79]:
a3[0::2,0::3,0::2]

array([[[ 0,  2]],

       [[18, 20]]])

# Iterating

In [86]:
a1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [83]:
for i in a1 :
  print(i)

0
1
2
3
4
5
6
7
8
9


In [85]:
a2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [84]:
for i in a2:
  print(i)

[0 1 2 3]
[4 5 6 7]
[ 8  9 10 11]


In [82]:
a3

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [88]:
for i in a3:
  print(i)

[[0 1 2]
 [3 4 5]
 [6 7 8]]
[[ 9 10 11]
 [12 13 14]
 [15 16 17]]
[[18 19 20]
 [21 22 23]
 [24 25 26]]


In [89]:
# element wise iteration(np.nditer)
for i in np.nditer(a3):
  print(i)

0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23
24
25
26


# Reshaping

In [91]:
# Transpose : Converts row to column
# np.transpose(a2)
a2.T

array([[ 0,  4,  8],
       [ 1,  5,  9],
       [ 2,  6, 10],
       [ 3,  7, 11]])

In [92]:
# ravel : converts any array to 1D array
a2.ravel()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

# Stacking

Stacking is the process of joining multiple arrays along a new axis (dimension)

Given the shape of the arrays to be stacked is same

In [94]:
a4 = np.arange(12).reshape(3,4)
a5 = np.arange(12,24).reshape(3,4)
a5

array([[12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [95]:
a4

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [96]:
# horizontal stacking : joins horizontally
np.hstack((a4,a5))

array([[ 0,  1,  2,  3, 12, 13, 14, 15],
       [ 4,  5,  6,  7, 16, 17, 18, 19],
       [ 8,  9, 10, 11, 20, 21, 22, 23]])

In [97]:
# vertical stacking : joins vertically
np.vstack((a4,a5))

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

# Splitting
Splitting is the opposite of stacking—it is used to divide an array into multiple sub-arrays.

In [98]:
# horizontal split
a4

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [101]:
np.hsplit(a4,2) # here 2 represents no. of sections you want to split it in ; should be even

[array([[0, 1],
        [4, 5],
        [8, 9]]),
 array([[ 2,  3],
        [ 6,  7],
        [10, 11]])]

In [102]:
# Vertical split
np.vsplit(a4,3)

[array([[0, 1, 2, 3]]), array([[4, 5, 6, 7]]), array([[ 8,  9, 10, 11]])]